### ISSUE TITLE
How to dump BGP RIB into MRT format file?

### ISSUE THREAD

**Issue by amiduai** [CSUNetSec/netsec-protobufs#1]
I installed FRR on ubuntu 18.04 LTS to simulate a router, which established a BGP session with another real router successfully.

I tried to dump the BGP RIB by using  dump command like 

'dump bgp mrt-route dumpfile '  
'dump bgp mrt-route /var/dumpfile 1h' . 

But after I typed these commands , I got nothing.
No error message.
And I can't find any 'dumpfile' in my filesystem of ubuntu 18.04 TLS.  

did I do something wrong? Does anyone know how to dump BGP RIB in FRR?  Thanks

**Comment by amiduai** [comment]
sorry, I got wrong place .

**Comment by ramrunner** [comment]
hey @amiduai did it work? let me know if you need any more help on dumping a RIB.

**Comment by amiduai** [comment]
The problem is about FRR. nothing to do  with this project.  Do you know how to dump RIB with FRR?
